[general]
type              = 2            # 1:encrypt   2:decrypt
encrypt_key       =              #
#plain_dir         = D:\github\OneNote±Ê¼Ç±¾\ORACLE
plain_dir         = D:\github\OneNote_plain\ORACLE
include_suffix    = .one
exclude_dir_name  = OneNote_RecycleBin
encrypt_dir       = D:\github\OneNote_enc\ORACLE
